version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:$DJANGO_PORT
    env_file:
      - .env
    environment:
      - DJANGO_DB_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "$DJANGO_PORT:$DJANGO_PORT"
    depends_on: [db]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: [.venv, node_modules, .db_data]
        - action: rebuild
          path: pyproject.toml

volumes:
  db_data: