version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:$DJANGO_PORT
    env_file:
      - .env
    environment:
      - DJANGO_DB_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    depends_on: [db]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: [.venv, node_modules, .db_data, media, static]
        - action: rebuild
          path: pyproject.toml

  proxy:
    image: caddy:alpine
    depends_on:
      - app
    env_file: [.env]
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./media:/media:ro
      - ./static:/static:ro

volumes:
  db_data:
  caddy_data:
  caddy_config: