# Generated by Django 5.0.1 on 2024-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_category_options_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.TextField(default=""),
        ),
    ]
