# Generated by Django 5.0.1 on 2024-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_productimage_options_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
